=== JcBprice/HTML-PROJEKT/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="naglowek">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="logo"/>
              <xs:element type="xs:string" name="web-title"/>
              <xs:element type="xs:string" name="web-subtitle"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="menu">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="item" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="glowna">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="tytul"/>
              <xs:element type="xs:string" name="tresc"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="wybor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tabela">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="rower" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="opis"/>
                          <xs:element name="czego-szukac">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="content" maxOccurs="unbounded" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="rodzaj" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JcBprice/HTML-PROJEKT/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
        <naglowek>
            <logo>LOGO</logo>
            <web-title>Rowery.info</web-title>
            <web-subtitle>Strona o rowerach i trasach rowerowych</web-subtitle>
        </naglowek>
        <menu>
            <item>Pasek nawigacji</item>
            <item>Strona główna</item>
            <item>Wybór roweru</item>
            <item>Trasy TPK</item>
        </menu>

        <glowna>
            <tytul>Wstęp</tytul>
            <tresc>
                Witaj na Stronie Głównej Pasjonatów Rowerów i TTPK!

                Zanurz się w fascynującym świecie jazdy na dwóch kółkach i odkryj uroki Trójmiejskiego Parku Krajobrazowego na wyjątkowych trasach rowerowych. Jesteśmy tu, by wspólnie z Tobą stworzyć niezapomniane przygody na jednym z najpiękniejszych obszarów Polski!
                
                Nasza Misja: Rowery i TTPK w Jednym Miejscu
                
                Łączymy pasję do rowerów z miłością do natury, oferując kompleksowe wsparcie w wyborze idealnego roweru do podboju Trójmiejskiego Parku Krajobrazowego. Niezależnie od tego, czy jesteś doświadczonym kolarzem czy dopiero zaczynasz swoją przygodę z pedałowaniem, u nas znajdziesz inspiracje, porady i informacje, które pomogą Ci w pełni cieszyć się każdą trasą.
                
                Co Oferujemy:
                
                Ekscytujące Trasy TTPK: Poznaj najpiękniejsze zakątki Trójmiejskiego Parku Krajobrazowego, odkrywając ukryte ścieżki i malownicze widoki. Nasze rekomendacje tras dopasowane są do różnych poziomów umiejętności i preferencji, aby każdy mógł znaleźć coś dla siebie.
                
                Porady w Wyborze Roweru: Niezdecydowany co do wyboru roweru? Nasi eksperci są tutaj, aby pomóc! Przygotowaliśmy poradniki, recenzje i testy, które ułatwią Ci podjęcie właściwej decyzji. Niezależnie od tego, czy preferujesz górskie wertepy, szosowe wyprawy czy relaksujące przejażdżki miejskim terenem – mamy rowery dla każdego.
                
                Społeczność Rowerowa: Dołącz do społeczności pasjonatów rowerów, dziel się swoimi przeżyciami, pytaj o rady i planuj wspólne wyprawy. Razem tworzymy wspólnotę, która celebrowe zdrowy tryb życia i miłość do aktywności na świeżym powietrzu.
                
                Rowerem przez TTPK - Twoja Przygoda Zaczyna Się Tutaj!
                
                Zapraszamy do odkrywania piękna Trójmiejskiego Parku Krajobrazowego na rowerze. Niech każdy pedał będzie pretekstem do nowych odkryć, a każda trasa przyniesie niezapomniane chwile. Dołącz do naszej społeczności i zanurz się w świecie, gdzie rower staje się kluczem do nieograniczonych przygód!
            </tresc>
        </glowna>
        <wybor>
            <tabela>
                <rower rodzaj="gorski">
                    <opis>Rower przeznaczony do jazdy w terenie górskim, idealny dla miłośników przygód na szlakach terenowych.</opis>
                    <czego-szukac>
                        <content>Pełne zawieszenie vs. hardtail</content>
                        <content>Rodzaj hamulców (tarczowe, v-brake)</content>
                        <content>Grubość opony i rodzaj bieżnika</content>
                        <content>Materiał ramy (aluminiowa, karbonowa)</content>
                    </czego-szukac>
                </rower>
                <rower rodzaj="miejski">
                    <opis>Rower dedykowany do codziennego transportu w miejskim otoczeniu, zapewniający wygodę i funkcjonalność.</opis>
                    <czego-szukac>
                        <content>Geometria ramy zapewniająca wygodną pozycję</content>
                        <content>Funkcje miejskie, takie jak oświetlenie LED i błotniki</content>
                        <content>Liczba biegów i rodzaj przerzutek</content>
                        <content>Solidne hamulce do bezpiecznych zatrzymań</content>
                    </czego-szukac>
                </rower>
                <rower rodzaj="szosowy">
                    <opis>Rower stworzony do szybkiej jazdy po utwardzonych drogach, idealny dla entuzjastów wyścigów i rekreacyjnych tras.</opis>
                    <czego-szukac>
                        <content>Lekka rama z aluminium lub karbonu</content>
                        <content>Aero-geometria dla zwiększenia prędkości</content>
                        <content>Wysokiej jakości osprzęt, takie jak przerzutki i hamulce</content>
                        <content>Opony o niskim oporze toczenia</content>
                    </czego-szukac>
                </rower>
                <rower rodzaj="trekkingowy">
                    <opis>Rower stworzony do szybkiej jazdy po utwardzonych drogach, idealny dla entuzjastów wyścigów i rekreacyjnych tras.</opis>
                    <czego-szukac>
                        <content>Wygodna geometria ramy dla długich tras</content>
                        <content>System mocowania bagażu (bagażniki, sakwy)</content>
                        <content>Odpowiedni zakres przerzutek do pokonywania różnych terenów</content>
                        <content>Solidne hamulce do bezpiecznej jazdy w różnych warunkach</content>
                    </czego-szukac>
                </rower>
            </tabela>
        </wybor>
    </root>
